name: 'practicefusion_connector'
version: '0.1.1'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_vytalize'

vars:
  exclude_packages: ["all"]
  input_database: "{% if var('ENV', 'dev') == 'dev' %}dev{% elif var('ENV', 'prod') == 'prod' %}main{% elif var('ENV', 'stage') == 'stage' %}tuva_test{% endif %}"
  input_schema: practicefusion
  clinical_enabled: true


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

models:
  practicefusion_connector:
    staging:
      +materialized: table
      +schema: stg_practicefusion
      +tags: staging
    intermediate:
      +materialized: table
      +schema: int_practicefusion
      +tags: intermediate
    final:
      +materialized: table
      +schema: input_layer
      +tags: input_layer
