name: connector_template
version: "1.0.0"
config-version: 2
require-dbt-version: ">=1.10.5,<3.0.0"

profile: default

flags:
  require_ref_searches_node_package_before_root: true

models:
  connector_template:
    +schema: input_layer
    +tags: [input_layer]
    final:
      +materialized: table

vars:
  claims_enabled: true
  clinical_enabled: false
  provider_attribution_enabled: false
  data_quality_enabled: false

  passthrough:
    prefix: "x_"
    strip: false
