name: connector_template
version: "1.0.0"
config-version: 2

profile: default

flags:
  require_ref_searches_node_package_before_root: true

models:
  connector_template:
    +schema: input_layer
    final:
      +materialized: table

vars:
  claims_enabled: true
  clinical_enabled: false
  provider_attribution_enabled: false
  semantic_layer_enabled: false
