with unfiltered_data as (
    select condition_id,
       person_id,
       patient_id,
       encounter_id,
       claim_id,
       recorded_date,
       onset_date,
       resolved_date,
       status,
       condition_type,
       source_code_type,
       source_code,
       source_description,
       normalized_code_type,
       normalized_code,
       normalized_description,
       condition_rank,
       present_on_admit_code,
       presend_on_admit_description,
       data_source,
       file_name,
       ingest_datetime,
       row_number() OVER(PARTITION BY condition_id ORDER BY file_name desc) as row_number
    from {{ ref('int_practicefusion_condition') }}
)
select condition_id,
    person_id,
    patient_id,
    encounter_id,
    claim_id,
    recorded_date,
    onset_date,
    resolved_date,
    status,
    condition_type,
    source_code_type,
    source_code,
    source_description,
    normalized_code_type,
    normalized_code,
    normalized_description,
    condition_rank,
    present_on_admit_code,
    presend_on_admit_description,
    data_source,
    file_name,
    ingest_datetime
from unfiltered_data
where row_number = 1
and (source_code is not null or source_description is not null)
