-- PracticeFusion does not have location data, so select placeholder nulls so TUVA model doesn't error out
select location_id,
       npi,
       name,
       facility_type,
       parent_organization,
       address,
       city,
       state,
       zip_code,
       latitude,
       longitude,
       data_source,
       file_name,
       ingest_datetime
from values ((null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null)) as null_values(location_id,
                                    npi,
                                    name,
                                    facility_type,
                                    parent_organization,
                                    address,
                                    city,
                                    state,
                                    zip_code,
                                    latitude,
                                    longitude,
                                    data_source,
                                    file_name,
                                    ingest_datetime)
