with unfiltered_data as (
    select person_id,
       patient_id,
       first_name,
       last_name,
       sex,
       race,
       birth_date,
       death_date,
       death_flag,
       social_security_number,
       address,
       city,
       state,
       zip_code,
       county,
       latitude,
       longitude,
       phone,
       data_source,
       file_name,
       ingest_datetime,
       row_number() OVER(PARTITION BY patient_id ORDER BY file_name desc) as row_number
from {{ ref('int_practicefusion_patient') }}
)
select person_id,
    patient_id,
    first_name,
    last_name,
    sex,
    race,
    birth_date,
    death_date,
    death_flag,
    social_security_number,
    address,
    city,
    state,
    zip_code,
    county,
    latitude,
    longitude,
    phone,
    data_source,
    file_name,
    ingest_datetime
from unfiltered_data
where row_number = 1